name: dh_schedule_generatorutb
description: Generador de horarios para estudiantes de UTB

version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  pdf: ^3.11.3
  path_provider: ^2.1.5
  path_provider_windows: ^2.1.3
  open_file: ^3.5.10
  csv: ^6.0.0
  excel: ^4.0.6
  collection: ^1.16.0
  diacritic: ^0.1.3
  universal_html: ^2.2.4
  cupertino_icons: ^1.0.2
  permission_handler: ^12.0.1
  http: ^1.4.0
  url_launcher: ^6.3.0
  url_strategy: ^0.3.0
  flutter_lints: ^6.0.0
  firebase_core: ^3.15.1
  firebase_analytics: ^11.5.2
  flutter_speed_dial: ^7.0.0
  web: ^1.1.1
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Roboto-Regular.ttf
    - images/logo.png
    - images/logo_utb.svg
    - images/utb.png

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DM_Sans/static/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DM_Sans/static/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DM_Sans/static/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DM_Sans/static/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DM_Sans/static/DMSans-Italic.ttf
          weight: 400
          style: italic
